/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SJ02Panel.java
 *
 * Created on 2011-3-19, 16:40:13
 */

package demo;

import demo.algorithms.SJ02;
import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import org.jdesktop.application.Action;

/**
 *
 * @author Kuloud
 */
public class SJ02Panel extends javax.swing.JPanel {
    private JDialog errorReport;

    /** Creates new form SJ02Panel */
    public SJ02Panel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(640, 429));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextArea1.setColumns(20);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(demo.DemoApp.class).getContext().getResourceMap(SJ02Panel.class);
        jTextArea1.setFont(resourceMap.getFont("jTextArea1.font")); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setName("jTextArea1"); // NOI18N
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextArea1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTextArea2.setColumns(20);
        jTextArea2.setFont(resourceMap.getFont("jTextArea2.font")); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setName("jTextArea2"); // NOI18N
        jTextArea2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextArea2KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTextArea2);

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        jTextArea3.setBackground(resourceMap.getColor("jTextArea3.background")); // NOI18N
        jTextArea3.setColumns(20);
        jTextArea3.setEditable(false);
        jTextArea3.setFont(resourceMap.getFont("jTextArea3.font")); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setName("jTextArea3"); // NOI18N
        jScrollPane3.setViewportView(jTextArea3);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(demo.DemoApp.class).getContext().getActionMap(SJ02Panel.class, this);
        jButton1.setAction(actionMap.get("run")); // NOI18N
        jButton1.setFont(resourceMap.getFont("jButton1.font")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        jButton2.setAction(actionMap.get("clear")); // NOI18N
        jButton2.setFont(resourceMap.getFont("jButton2.font")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N

        jButton3.setAction(actionMap.get("readIntA")); // NOI18N
        jButton3.setIcon(resourceMap.getIcon("jButton3.icon")); // NOI18N
        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N

        jButton4.setAction(actionMap.get("readIntB")); // NOI18N
        jButton4.setIcon(resourceMap.getIcon("jButton4.icon")); // NOI18N
        jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
        jButton4.setName("jButton4"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1)
                                .addComponent(jButton2))
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3, jButton4});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jScrollPane2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jButton4, 0, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(11, 11, 11)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2, jButton3, jButton4});

    }// </editor-fold>//GEN-END:initComponents

    private void jTextArea1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyPressed
        // TODO add your handling code here:
        kRun(evt);
    }//GEN-LAST:event_jTextArea1KeyPressed

    private void jTextArea2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea2KeyReleased
        // TODO add your handling code here:
        kRun(evt);
    }//GEN-LAST:event_jTextArea2KeyReleased

    @Action
    public void readIntA(){
        JFileChooser fc = new JFileChooser();
        int option = fc.showOpenDialog(getParent());
        if (JFileChooser.APPROVE_OPTION == option) {
            FileReader frA = null;
            try {
                frA = new FileReader(fc.getSelectedFile());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(SJ02Panel.class.getName()).log(Level.SEVERE, null, ex);
            }
            Scanner scanA = new Scanner(frA);
            if(scanA.hasNextBigInteger()) {
                jTextArea1.setText(scanA.nextBigInteger().toString());
            }else {
                jTextArea1.setText("文本错误！请选择正确文件或重新输入。");
                jTextArea1.requestFocus();
                jTextArea1.selectAll();
            }
        }
    }

    @Action
    public void readIntB() {
        JFileChooser fc = new JFileChooser();
        int option = fc.showOpenDialog(getParent());
        if (JFileChooser.APPROVE_OPTION == option) {
            FileReader frB = null;
            try {
                frB = new FileReader(fc.getSelectedFile());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(SJ02Panel.class.getName()).log(Level.SEVERE, null, ex);
            }
            Scanner scanB = new Scanner(frB);
            if(scanB.hasNextBigInteger()) {
                jTextArea2.setText(scanB.nextBigInteger().toString());
            }else {
                jTextArea2.setText("文本错误！请选择正确文件或重新输入。");
                jTextArea2.requestFocus();
                jTextArea2.selectAll();
            }
        }
    }

    @Action
    public void clear() {
        jTextArea1.setText("");
        jTextArea2.setText("");
        jTextArea3.setText("");
    }

    @Action
    public void run() {
        boolean flag = false;
        String strA = jTextArea1.getText().trim();
        String strB = jTextArea2.getText().trim();
        if(strA.charAt(0) == '-') {
            strA = strA.substring(1);
            flag = true;
        }
        if(strB.charAt(0) == '-') {
            strB = strB.substring(1);
            flag = true;
        }
        
        SJ02.strProcess = new StringBuffer("两大整数乘法运算过程：");
        if(flag) {
            SJ02.strProcess.append("\n有负数，略去负号进行运算……");
        }
        try {
            String strResult = SJ02.BigIntMultDif(strA, strB,0);
        } catch (Exception e) {
            jTextArea3.setText("");
            if (errorReport == null) {
                JFrame mainFrame = DemoApp.getApplication().getMainFrame();
                errorReport = new ErrorReport(mainFrame, false);
                errorReport.setLocationRelativeTo(mainFrame);
            }
            DemoApp.getApplication().show(errorReport);
            jTextArea1.requestFocus();
            return;
        }
        
        jTextArea3.setText(SJ02.strProcess.toString());
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
    private void kRun(KeyEvent evt) {
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            run();
        }
    }
}
